[project]
name = "building-llm-applications-from-scratch"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "nltk>=3.9.2",
    "pytorch-transformers>=1.2.0",
]
